### ISSUE TITLE
Scannet dont extract depth map，is it necessary？

### ISSUE THREAD

**Issue by 2bHansome** [ttaoREtw/ImGeoNet#5]
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/mmdet/datasets/dataset_wrappers.py", line 151, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/ssh/ImGeoNet/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 294, in __getitem__
    data = self.prepare_train_data(idx)
  File "/ssh/ImGeoNet/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 151, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/ssh/ImGeoNet/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 577, in __call__
    dep_map = np.array(imageio.imread(path))
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/imageio/v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/imageio/core/imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/imageio/core/request.py", line 247, in __init__
    self._parse_uri(uri)
  File "/opt/conda/envs/imgeonet/lib/python3.8/site-packages/imageio/core/request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/ssh/ImGeoNet/data/scannet/posed_images/scene0127_01/00012.png'

**Comment by ttaosci** [comment]
Yes, it is necessary for training ImGeoNet.
Please refer to this function: https://github.com/ttaoREtw/ImGeoNet/blob/6f0c27534e94af809e41705f88f1f838f7fb554a/data/scannet/extract_posed_images.py#L99C9-L99C28
